import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getEditorialImagesEnvironment } from '../src/environment.js';
import type { EditorialImageReference } from '../src/services/editorial-images.js';
import { PexelsEditorialImageProvider } from '../src/services/pexels-editorial-images.js';

/**
 * Resolves the two editorial photographs the signed-out landing pins at rest.
 *
 * The landing is unauthenticated traffic: it must never call the editorial
 * image service per visitor, so its photographs cannot go through the normal
 * `resolveEditorialImages` client path (which requires a Supabase session and
 * would 401 for a signed-out request anyway). Instead this script resolves a
 * small, curated set of subjects once, out-of-band, and writes them to a
 * committed TypeScript module the landing/auth surfaces import directly.
 *
 * Subjects are generic scene descriptions, not real place names, so the
 * photographs stay honestly decorative (PRD 4.8: an editorial photograph
 * never claims to depict an exact place).
 *
 * Usage:
 *   PEXELS_API_KEY must already be set in the repo-root .env (it is loaded by
 *   `../src/environment.js`).
 *
 *   pnpm --filter @trove/api exec tsx scripts/resolve-landing-editorial-images.ts
 *
 * Re-run and commit the regenerated `apps/web/lib/media/landing-images.ts` in
 * its own PR whenever the landing photographs need to be refreshed.
 */

const LANDING_IMAGE_SUBJECTS = [
  {
    category: 'destination',
    exportName: 'landingHeroImage',
    name: 'coastal cliff road at golden hour',
  },
  {
    category: 'destination',
    exportName: 'landingLiveItImage',
    name: 'traveler walking through old town street',
  },
] as const;

const HEADER_COMMENT = `// GENERATED by apps/api/scripts/resolve-landing-editorial-images.ts — do not hand-edit.
//
// Landing imagery is pinned at rest (PRD 4.8 / WDL-176): the signed-out
// landing and auth surfaces are unauthenticated traffic, so an anonymous page
// load must cost zero editorial-image provider calls. These references were
// resolved once, out-of-band, and are committed rather than fetched per
// visitor.
//
// To refresh: set PEXELS_API_KEY in the repo-root .env and re-run
//   pnpm --filter @trove/api exec tsx scripts/resolve-landing-editorial-images.ts
// then review the new photographs and attribution and commit this file in
// its own PR.`;

function toWebReference(reference: EditorialImageReference) {
  return reference;
}

function renderModule(resolvedAt: string, images: Record<string, EditorialImageReference>) {
  const exportedConstants = Object.entries(images)
    .map(
      ([exportName, reference]) =>
        `export const ${exportName}: EditorialImageReference = ${JSON.stringify(toWebReference(reference), null, 2)};`,
    )
    .join('\n\n');

  return `${HEADER_COMMENT}

import type { EditorialImageReference } from './editorial-images';

export const LANDING_IMAGES_RESOLVED_AT = '${resolvedAt}';

${exportedConstants}
`;
}

async function main() {
  const environment = getEditorialImagesEnvironment();

  if (!environment) {
    throw new Error(
      'PEXELS_API_KEY is not configured (or TROVE_EDITORIAL_IMAGES_DISABLED is set). ' +
        'Set PEXELS_API_KEY in the repo-root .env before running this script.',
    );
  }

  const provider = new PexelsEditorialImageProvider({
    apiKey: environment.pexelsApiKey,
    hourlyBudget: environment.hourlyBudget ?? 150,
    source: 'editorial-images',
  });

  const resolved: Record<string, EditorialImageReference> = {};

  for (const subject of LANDING_IMAGE_SUBJECTS) {
    const [image] = await provider.search({
      category: subject.category,
      kind: 'generic',
      name: subject.name,
    });

    if (!image) {
      throw new Error(
        `No photograph resolved for landing subject "${subject.name}" (${subject.exportName}). ` +
          'Pick a different subject and re-run.',
      );
    }

    resolved[subject.exportName] = image;
    console.log(
      `Resolved ${subject.exportName}: photo by ${image.attribution.photographerName} (${image.attribution.providerPageUrl})`,
    );
  }

  const resolvedAt = new Date().toISOString().slice(0, 10);
  const outputPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../../web/lib/media/landing-images.ts',
  );

  await writeFile(outputPath, renderModule(resolvedAt, resolved), 'utf8');

  console.log(`\nWrote ${outputPath}`);
  console.log(
    'Review the photographs and attribution above, then run prettier and commit ' +
      'apps/web/lib/media/landing-images.ts in its own PR.',
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
