// GENERATED by apps/api/scripts/resolve-landing-editorial-images.ts — do not hand-edit.
//
// Landing imagery is pinned at rest (PRD 4.8 / WDL-176): the signed-out
// landing and auth surfaces are unauthenticated traffic, so an anonymous page
// load must cost zero editorial-image provider calls. These references were
// resolved once, out-of-band, and are committed rather than fetched per
// visitor.
//
// To refresh: set PEXELS_API_KEY in the repo-root .env and re-run
//   pnpm --filter @trove/api exec tsx scripts/resolve-landing-editorial-images.ts
// then review the new photographs and attribution and commit this file in
// its own PR.

import type { EditorialImageReference } from './editorial-images';

export const LANDING_IMAGES_RESOLVED_AT = '2026-08-23';

export const landingHeroImage: EditorialImageReference = {
  altText: 'Breathtaking coastal view with ocean, cliffs, and cars on a winding road at sunset.',
  attribution: {
    photographerName: 'ArtHouse Studio',
    photographerUrl: 'https://www.pexels.com/@arthousestudio',
    providerName: 'pexels',
    providerPageUrl: 'https://www.pexels.com/photo/cars-on-road-near-body-of-water-8146248/',
  },
  dominantColor: '#716648',
  externalPhotoId: '8146248',
  height: 5956,
  sourceUrl: 'https://images.pexels.com/photos/8146248/pexels-photo-8146248.jpeg',
  width: 7944,
};

export const landingLiveItImage: EditorialImageReference = {
  altText:
    'A person with a yellow backpack walks through a narrow alley between brick walls, capturing a sense of exploration.',
  attribution: {
    photographerName: 'Helena Jankovičová Kováčová',
    photographerUrl: 'https://www.pexels.com/@helen1',
    providerName: 'pexels',
    providerPageUrl:
      'https://www.pexels.com/photo/traveler-walking-through-narrow-brick-alleyway-31075085/',
  },
  dominantColor: '#9A724E',
  externalPhotoId: '31075085',
  height: 4480,
  sourceUrl: 'https://images.pexels.com/photos/31075085/pexels-photo-31075085.jpeg',
  width: 6720,
};
